movieproject/movieapp/urls.py
from . import views
from django.contrib import admin
from django.urls import path

app_name='movieapp'

urlpatterns = [
    path('',views.home, name='home'),
    path('movie/<int:movie_id>/',views.detail,name="detail"),
    path('add',views.add_movie,name="add_movie"),
    path('update/<int:id>/',views.update,name="update"),
    path('delete/<int:id>/',views.delete,name="delete"),
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from . models import movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','year','desc','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import MovieForm
from . models import movie
# Create your views here.
def home(request):
    movies=movie.objects.all()
    context={
        'movie_list':movies
    }
    return render(request,"index.html",context)
def detail(request,movie_id):
    mov=movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':mov})

def add_movie(request):
    if request.method=='POST':
        name1=request.POST.get('name',)
        year1 = request.POST.get('year', )
        desc1 = request.POST.get('desc', )
        img1 = request.FILES['img']

        movieobj=movie(name=name1,year=year1,desc=desc1,img=img1)
        movieobj.save()

    return render(request,"add.html")

def update(request,id):
    movie1=movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie1)

    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html",{'movie':movie1,'form':form})

def delete(request,id):
    if request.method=='POST':
        movie1=movie.objects.get(id=id)
        movie1.delete()
        return redirect('/')
    return render(request,"delete.html")

movieproject/templates/add.html
{% extends 'base.html' %}
{% load static %}
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'style1.css' %}">
    {% endblock %}
{% block body %}
<div class="center">
    <h3>Add a new movie</h3>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="inputbox">
                <input type="text" name="name" placeholder="enter movie name"><br>
            </div>
            <div class="inputbox">
                <input type="number" name="year" placeholder="enter year"><br>
            </div>
            <div class="inputbox">
                <input type="text" name="desc" placeholder="enter description"><br>
            </div>
            <div class="inputbox">
                <input type="file" name="img"><br>
            </div>
            <div class="inputbox">
                <input type="submit">
            </div>
        </form>
    </div>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block css %}
    {% endblock %}
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="POST">

    {% csrf_token %}
    Do you really want to delete this movie?
    <input type="submit">
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'style1.css' %}">
{% endblock %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width=400 height=400><br>
        </div>
        <div class="col-md-6">
            <h3><b>{{movie.name}}</b></h3>
            <h4>{{movie.year}}</h4>
            <h5>{{movie.desc}}</h5>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>


{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'style1.css' %}">
{% endblock %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col=md-3">
            <div class="card" style="width: 18rem; margin-right:20px;margin-bottom:10px; margin-top:10px;">
              <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap"  height="250">
              <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>
                <h6 class="card-text">{{i.year}}</h6>
                <a href="{% url  'movieapp:detail' i.id %}" class="btn btn-primary">More Info</a>
              </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}